import { describe, expect, it } from "vitest";
import { evaluateCondition } from "../scripts/core/condition-service";
import { evaluateFormula, validateFormula } from "../scripts/core/formula-service";
import { resolveGrantGroup } from "../scripts/core/grant-service";
import { canUse, consume, shouldReset } from "../scripts/core/usage-service";
import { filterCatalog } from "../scripts/core/catalog-service";
import { AdapterRegistry } from "../scripts/adapters/adapter-registry";
import { DeityService } from "../scripts/core/deity-service";
import { GodForgeApi, type GodForgeActor } from "../scripts/api";
import { JournalDeityRepository } from "../scripts/foundry/journal-repository";
import { SocketRouter, type AuthorityContext, type SocketTransport } from "../scripts/foundry/socket-router";
import { executeAbility, type EffectTarget } from "../scripts/core/effect-engine";
import { resolveTargets } from "../scripts/core/target-service";
import { TriggerEngine } from "../scripts/core/trigger-engine";
import type { DeityDefinition } from "../scripts/core/types";

const deity: DeityDefinition = { id: "a", schemaVersion: 1, revision: 1, createdAt: "", updatedAt: "", checksum: "", name: "A", title: "T", description: "D", domains: ["shadow"], passiveBonuses: [], abilities: [], grantGroups: [], replacement: { sourceUuid: "", mode: "none", contexts: [] }, visibility: { library: true, players: true, characterSheet: true } };

describe("formula service", () => { it("evaluates whitelisted facts", () => expect(evaluateFormula("3 + @actor.level", { actor: { level: 4 }, target: {} })).toBe(7)); it("rejects code", () => expect(validateFormula("window.alert(1)")).toBe(false)); });
describe("conditions and grants", () => { it("evaluates nested boolean conditions", () => expect(evaluateCondition({ type: "and", children: [{ type: "fact", key: "level", equals: 5 }, { type: "not", child: { type: "fact", key: "dead", equals: true } }] }, { level: 5, dead: false })).toBe(true)); it("requires an exact pick", () => expect(resolveGrantGroup({ id: "g", mode: "any", pick: 1, label: "", grants: [{ type: "bonus", ref: "a" }] }, { groupId: "g", refs: ["a"] })).toEqual(["a"])); });
describe("usage", () => { it("consumes and resets daily uses", () => { const state = { used: 0, max: 1, lastResetAt: 0, reset: "daily" as const }; expect(canUse(state, 0)).toBe(true); expect(consume(state, 0).used).toBe(1); expect(shouldReset({ ...state, used: 1 }, 86400000)).toBe(true); }); });
describe("catalog", () => { it("filters hidden and pantheon entries", () => expect(filterCatalog([deity, { ...deity, id: "b", domains: ["fire"] }], { pantheonFilter: "shadow" }, new Set(["a"]))).toEqual([])); });
describe("system adapters", () => { it("supports Pathfinder and Starfinder only", () => { const registry = new AdapterRegistry(); expect(registry.supports("pf2e")).toBe(true); expect(registry.supports("sf2e")).toBe(true); expect(registry.supports("sfrpg")).toBe(true); expect(registry.supports("dnd5e")).toBe(false); expect(() => registry.get("dnd5e")).toThrow(); }); });
describe("public API", () => { it("assigns, reads and removes an actor deity", async () => { const service = new DeityService(); service.save(deity); const actor: GodForgeActor = { id: "actor", flags: {}, update: async (data) => { actor.flags = data.flags; } }; const api = new GodForgeApi(service, new AdapterRegistry()); await api.assignDeity(actor, "a"); expect(api.getActorDeity(actor)?.id).toBe("a"); await api.removeDeity(actor); expect(api.getActorDeity(actor)).toBeNull(); }); });
describe("Foundry journal persistence", () => { it("loads and updates canonical deity flags", async () => { const journal = { id: "j", uuid: "Journal.j", name: "A", flags: { "darkis-godforge": { schemaVersion: 1, deity } }, update: async (data: Record<string, unknown>) => { journal.flags = data.flags as typeof journal.flags; } }; const repository = new JournalDeityRepository({ contents: [journal] }); expect(repository.load()[0]?.id).toBe("a"); await repository.save({ ...deity, revision: 2 }); expect(repository.load()[0]?.revision).toBe(2); }); });
describe("GM authority", () => { it("rejects a duplicate activation request", async () => { const service = new DeityService(); service.save({ ...deity, abilities: [{ id: "a1", name: "A", description: "", effects: [{ type: "message", text: "ok" }] }] }); const actor: GodForgeActor = { id: "actor", flags: { "darkis-godforge": { deityId: "a", grants: [], usages: {} } }, update: async () => undefined }; const authority: AuthorityContext = { currentUserId: "gm", isGM: true, ownsActor: () => true, resolveActor: () => actor }; let handler: ((payload: unknown) => Promise<unknown>) | undefined; const transport: SocketTransport = { register: (_name, callback) => { handler = callback; }, executeAsGM: async () => undefined }; const router = new SocketRouter(new GodForgeApi(service, new AdapterRegistry()), authority, transport); router.register(); const payload = { activationId: "fixed", actorId: "actor", userId: "gm", abilityId: "a1", options: {} }; await handler?.(payload); await expect(handler?.(payload)).rejects.toThrow("already been processed"); expect(router.status("fixed")).toBe("completed"); }); });
describe("trigger and target automation", () => { it("dispatches only indexed triggers", async () => { const engine = new TriggerEngine(); const ability = { id: "a", name: "", description: "", trigger: "manual", effects: [] as [] }; engine.register("d", ability); let count = 0; expect(await engine.dispatch("manual", { facts: {}, execute: async () => { count += 1; } })).toBe(1); expect(count).toBe(1); }); it("resolves area targets and evaluates effect branches", async () => { const actor: EffectTarget = { id: "a", hp: 10, maxHp: 10, modifiers: {}, conditions: [] }; const target: EffectTarget = { id: "b", hp: 10, maxHp: 10, modifiers: {}, conditions: [] }; const result = await executeAbility({ id: "x", name: "", description: "", effects: [{ type: "branch", condition: { type: "fact", key: "level", equals: 5 }, then: [{ type: "message", text: "yes" }] }] }, { actor, target, facts: { actor: { level: 5 }, target: {} }, conditionFacts: { level: 5 } }); expect(result.messages).toEqual(["yes"]); expect(resolveTargets(actor, [actor, target], { mode: "area" })).toEqual([target]); }); });
