import type { GodForgeActor, GodForgeApi } from "../api";
import type { DeityService } from "../core/deity-service";
import { gmApplicationBase } from "../foundry/application-base";
import { uiText } from "../foundry/i18n";
import { requireGM } from "../foundry/permissions";
import { getFoundryGame, getFoundryUi } from "../foundry/runtime";
import { reportActionError } from "../foundry/error-reporting";
import { collectGrantChoiceGroups } from "../core/grant-choice-service";

export class GodForgeCharacterManager extends gmApplicationBase() {
  static DEFAULT_OPTIONS = { id: "darkis-godforge-character-manager", classes: ["darkis-godforge"], window: { title: "DARKIS_GODFORGE.UI.CHARACTERS", resizable: true }, position: { width: 900, height: 700 } };
  static PARTS = { main: { template: "modules/darkis-godforge/templates/character-manager.hbs" } };
  constructor(private readonly deities: DeityService, private readonly api: GodForgeApi) { super(); }
  async _prepareContext(): Promise<Record<string, unknown>> { requireGM(); const actors = (getFoundryGame()?.actors?.contents ?? []).flatMap((value) => { const actor = value as GodForgeActor & { name?: string; type?: string }; if (actor.type && actor.type !== "character") return []; const state = actor.flags?.["darkis-godforge"] as { deityId?: string } | undefined; const deity = this.deities.get(state?.deityId ?? ""); return [{ id: actor.id, name: actor.name ?? actor.id, deityName: deity?.name ?? "—", hasDeity: Boolean(deity) }]; }); const deities = this.deities.list().filter((deity) => deity.kind !== "lore" && deity.status !== "archived").map((deity) => ({ id: deity.id, name: deity.name, choiceGroups: deity.grantGroups.flatMap((group) => collectGrantChoiceGroups(group)) })); return { ui: uiText(), actors, deities }; }
  _onRender(): void { requireGM(); const root = this.element; const deitySelect = root?.querySelector<HTMLSelectElement>("[name='deityId']"); const updateChoices = () => root?.querySelectorAll<HTMLElement>("[data-deity-choices]").forEach((section) => { section.hidden = section.dataset.deityChoices !== deitySelect?.value; }); deitySelect?.addEventListener("change", updateChoices); updateChoices(); root?.querySelector<HTMLFormElement>("form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const data = new FormData(form); const actor = getFoundryGame()?.actors?.get(String(data.get("actorId") ?? "")) as GodForgeActor | undefined; const deityId = String(data.get("deityId") ?? ""); if (!actor || !deityId) return; const choices: Record<string, string[]> = {}; root.querySelectorAll<HTMLInputElement>(`[data-deity-choices='${cssEscape(deityId)}'] input[data-group]:checked`).forEach((input) => { (choices[input.dataset.group ?? ""] ??= []).push(input.value); }); void this.api.assignDeity(actor, deityId, choices).then(() => this.render(true)).catch((error: unknown) => reportActionError("Character assignment failed.", error)); }); root?.querySelectorAll<HTMLButtonElement>("[data-action='reset-daily-usages']").forEach((button) => button.addEventListener("click", () => { const actor = getFoundryGame()?.actors?.get(button.dataset.actorId ?? "") as GodForgeActor | undefined; if (!actor) return; button.disabled = true; void this.api.resetActorUsages(actor, "daily-preparations").then(() => { getFoundryUi()?.notifications?.info?.(uiText().RESET_DAILY_COMPLETE ?? "Daily-preparation uses were reset."); return this.render(true); }).catch((error: unknown) => { button.disabled = false; reportActionError("Daily usage reset failed.", error); }); })); }
}

function cssEscape(value: string): string { return typeof CSS !== "undefined" ? CSS.escape(value) : value.replace(/["'\\]/g, "\\$&"); }
