import type { DeityService } from "../core/deity-service";

type ApplicationBase = { render(force?: boolean): void };
function foundryApp(): new (...args: never[]) => ApplicationBase { return (globalThis as { foundry?: { applications?: { api?: { ApplicationV2?: new (...args: never[]) => ApplicationBase } } } }).foundry?.applications?.api?.ApplicationV2 ?? class { render(): void { /* preview fallback */ } }; }

export class GodForgeCodex extends foundryApp() {
  constructor(private readonly deityService: DeityService) { super(); }
  override render(force = false): void { void force; const host = document.createElement("div"); host.className = "dg-codex dg-detail"; host.innerHTML = `<button class="dg-close" data-close>×</button><div class="dg-codex-title"><p class="eyebrow">DARKIS GODFORGE</p><h2>Götterkodex</h2><p class="muted">Durchsuche dein Pantheon und entdecke seine Geschichten.</p></div><div class="dg-codex-toolbar"><input data-search placeholder="Götter durchsuchen..."><select data-filter><option value="">Alle Domänen</option>${[...new Set(this.deityService.list().flatMap((deity) => deity.domains))].sort().map((domain) => `<option value="${domain}">${domain}</option>`).join("")}</select></div><div class="dg-codex-list" data-list></div>`; document.body.append(host); host.querySelectorAll<HTMLElement>("[data-close]").forEach((button) => button.addEventListener("click", () => host.remove())); const search = host.querySelector<HTMLInputElement>("[data-search]"); const filter = host.querySelector<HTMLSelectElement>("[data-filter]"); const refresh = (): void => { const term = search?.value.toLocaleLowerCase() ?? ""; const domain = filter?.value ?? ""; const entries = this.deityService.list().filter((deity) => (!term || `${deity.name} ${deity.title}`.toLocaleLowerCase().includes(term)) && (!domain || deity.domains.includes(domain))); const list = host.querySelector<HTMLElement>("[data-list]"); if (list) list.innerHTML = entries.map((deity) => `<article class="dg-codex-entry"><div><h3>${deity.name}</h3><p>${deity.title}</p></div><span>${deity.domains.slice(0, 3).join(" · ")}</span></article>`).join("") || `<p class="muted">Keine Gottheiten gefunden.</p>`; }; search?.addEventListener("input", refresh); filter?.addEventListener("change", refresh); refresh(); }
}
