import type { DeityService } from "../core/deity-service";
import type { DeityDefinition } from "../core/types";
import { GodForgeDeityEditor } from "./deity-editor";
import { GodForgeCodex } from "./codex";
import { escapeHtml, safeImageUrl } from "../core/sanitize";

type ApplicationBase = { render(force?: boolean): void };
function foundryApp(): new (...args: never[]) => ApplicationBase { return (globalThis as { foundry?: { applications?: { api?: { ApplicationV2?: new (...args: never[]) => ApplicationBase } } } }).foundry?.applications?.api?.ApplicationV2 ?? class { render(): void { /* preview fallback */ } }; }

export class GodForgeDashboard extends foundryApp() {
  static DEFAULT_OPTIONS = { id: "darkis-godforge-dashboard", classes: ["darkis-godforge"], window: { title: "DARKIS_GODFORGE.UI.TITLE" } };
  private readonly deityService: DeityService;
  constructor(deityService: DeityService) { super(); this.deityService = deityService; }
  override render(force = false): void { void force; const host = document.createElement("div"); host.className = "dg-dashboard"; host.innerHTML = this.template(this.deityService.list()); document.body.append(host); host.querySelectorAll<HTMLElement>("[data-deity]").forEach((card) => card.addEventListener("click", () => this.showDetail(card.dataset.deity ?? ""))); host.querySelectorAll<HTMLElement>("[data-create]").forEach((button) => button.addEventListener("click", () => new GodForgeDeityEditor(this.deityService, () => { host.remove(); this.render(true); }).render(true))); host.querySelectorAll<HTMLElement>("[data-codex]").forEach((button) => button.addEventListener("click", () => new GodForgeCodex(this.deityService).render(true))); }
  private template(deities: DeityDefinition[]): string { return `<header class="dg-hero"><img src="${safeImageUrl((globalThis as { DG_LOGO?: string }).DG_LOGO ?? "logo.png")}" alt="Darkis GodForge"><div><p class="eyebrow">DARKIS GODFORGE</p><h1>Götter erschaffen. Glauben formen.</h1><p class="muted">Schicksal schmieden.</p></div><div class="dg-hero-actions"><button class="dg-secondary" data-codex>Götterkodex</button><button class="dg-primary" data-create>＋ Neuen Gott erstellen</button></div></header><main><section class="dg-panel"><div class="dg-section-title"><h2>Meine Götter</h2><span>${deities.length} Einträge</span></div><div class="dg-grid">${deities.map((deity) => `<article class="dg-card" data-deity="${escapeHtml(deity.id)}"><div class="dg-card-art"><img src="${safeImageUrl(deity.image)}" alt=""></div><h3>${escapeHtml(deity.name)}</h3><p>${escapeHtml(deity.title)}</p><div class="dg-tags">${deity.domains.slice(0, 3).map((domain) => `<span>${escapeHtml(domain)}</span>`).join("")}</div></article>`).join("")}<button class="dg-card dg-add" data-create><span>＋</span><strong>Neuen Gott erstellen</strong><small>In dein Pantheon aufnehmen</small></button></div></section><section class="dg-stats"><div><strong>${deities.length}</strong><span>Gottheiten</span></div><div><strong>12</strong><span>Glaubensorte</span></div><div><strong>47</strong><span>Würfel-Boni</span></div><div><strong>9</strong><span>Rituale</span></div></section></main>`; }
  private showDetail(id: string): void { const deity = this.deityService.get(id); if (!deity) return; const panel = document.createElement("div"); panel.className = "dg-detail"; panel.innerHTML = `<button class="dg-close">×</button><div class="dg-detail-art"><img src="${safeImageUrl(deity.image)}" alt=""></div><div><p class="eyebrow">GÖTTLICHE DEFINITION</p><h2>${escapeHtml(deity.name)}</h2><p class="muted">${escapeHtml(deity.title)}</p><p>${escapeHtml(deity.description)}</p><div class="dg-tabs"><button class="active">Übersicht</button><button>Domänen</button><button>Fähigkeiten</button><button>Sichtbarkeit</button></div><div class="dg-detail-grid"><div><h3>Domänen</h3><div class="dg-list">${deity.domains.map((domain) => `<div>${escapeHtml(domain)}<span>＋1</span></div>`).join("")}</div></div><div><h3>Passiver Bonus</h3><div class="dg-callout"><strong>＋${escapeHtml(String(deity.passiveBonuses[0]?.value ?? 0))}</strong><span>${escapeHtml(deity.passiveBonuses[0]?.name ?? "Noch kein Bonus")}</span></div><h3>Göttliche Fähigkeit</h3><div class="dg-callout"><strong>${escapeHtml(deity.abilities[0]?.name ?? "Noch keine Fähigkeit")}</strong><span>${escapeHtml(deity.abilities[0]?.description ?? "Definiere dein erstes Wunder.")}</span></div></div></div></div>`; document.body.append(panel); panel.querySelector(".dg-close")?.addEventListener("click", () => panel.remove()); }
}
