import type { DeityService } from "../core/deity-service";
import type { DeityDefinition } from "../core/types";

type ApplicationBase = { render(force?: boolean): void };
function foundryApp(): new (...args: never[]) => ApplicationBase { return (globalThis as { foundry?: { applications?: { api?: { ApplicationV2?: new (...args: never[]) => ApplicationBase } } } }).foundry?.applications?.api?.ApplicationV2 ?? class { render(): void { /* preview fallback */ } }; }

export class GodForgeDeityEditor extends foundryApp() {
  constructor(private readonly deityService: DeityService, private readonly onSaved: (deity: DeityDefinition) => void) { super(); }
  override render(force = false): void { void force; const host = document.createElement("div"); host.className = "dg-editor dg-detail"; host.innerHTML = `<button class="dg-close" data-close>×</button><div class="dg-editor-header"><p class="eyebrow">DARKIS GODFORGE</p><h2>Neuen Gott erschaffen</h2><p class="muted">Definiere die Identität und die ersten Domänen deiner Gottheit.</p></div><form><label>Name<input name="name" required maxlength="80" placeholder="z. B. Tenebris"></label><label>Titel<input name="title" required maxlength="120" placeholder="z. B. Göttin der Schatten"></label><label>Beschreibung<textarea name="description" required maxlength="1000" rows="4"></textarea></label><label>Domänen<input name="domains" required placeholder="Schatten, Geheimnisse, Täuschung"></label><label>Ausrichtung<input name="alignment" placeholder="Neutral Böse"></label><div class="dg-editor-actions"><button type="button" data-close>Abbrechen</button><button class="dg-primary" type="submit">Gottheit speichern</button></div><p class="dg-form-error" role="alert"></p></form>`; document.body.append(host); host.querySelectorAll<HTMLElement>("[data-close]").forEach((button) => button.addEventListener("click", () => host.remove())); host.querySelector("form")?.addEventListener("submit", (event) => { event.preventDefault(); this.save(host); }); }
  private save(host: HTMLElement): void { const form = host.querySelector("form"); if (!(form instanceof HTMLFormElement)) return; const data = new FormData(form); try { const deity = this.deityService.create({ name: String(data.get("name") ?? "").trim(), title: String(data.get("title") ?? "").trim(), description: String(data.get("description") ?? "").trim(), domains: String(data.get("domains") ?? "").split(",").map((domain) => domain.trim()).filter(Boolean), alignment: String(data.get("alignment") ?? "").trim() || undefined, passiveBonuses: [], abilities: [], grantGroups: [], replacement: { sourceUuid: "", mode: "none", contexts: [] }, visibility: { library: true, players: true, characterSheet: true } }); this.onSaved(deity); host.remove(); } catch (error) { const message = host.querySelector<HTMLElement>(".dg-form-error"); if (message) message.textContent = error instanceof Error ? error.message : "Die Gottheit konnte nicht gespeichert werden."; } }
}
